
services:
  leadshub_web:
    container_name: leadshub_web
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      interactive_net:
        ipv4_address: 172.19.0.10

# networks:
#   interactive_net:
#     external: true
