services:
  leadshub_web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leadshub_web.rule=Host(`www.tecnoprohub.com`)"
      - "traefik.http.services.leadshub_web.loadbalancer.server.port=80"
      
networks:
  dokploy-network:
    external: true
