networks:
  interactive_net:
    external: true
    name: interactive_net

services:
  leadshub_web:
    container_name: "leadshub_web"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENV=${BUILD_ENV:-development}
    expose:
      - 80
    networks:
      interactive_net:
        ipv4_address: 172.19.0.12
    environment:
      - NODE_ENV=development
    labels:
      - traefik.enable=true
      - traefik.http.routers.leadshub-web.rule=Host(`${DOMAIN:-localhost}`)
      - traefik.http.routers.leadshub-web.entrypoints=web
      - traefik.http.services.leadshub-web.loadbalancer.server.port=80
