name: Deploy to VPS using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jsglobaltech/leadhub:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensure build is completed before deployment

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          key: ${{ secrets.VPS_SSH_KEY }}
          username: ${{ secrets.VPS_USER }}
          password: JaksonJose-1985
          script: |
            cd /opt/leadhub
            sudo docker-compose config  # Verifica a configuração do docker-compose
            sudo docker-compose pull
            sudo docker-compose up -d --no-deps --build --remove-orphans
            sudo docker image prune -f
